name: coastal_winds
channels:
  - conda-forge
dependencies:
  - cartopy=0.24.0
  - dask=2025.5.1
  - metpy=1.7.0
  - numpy=1.26.4
  - netcdf4=1.7.2
  - xarray=2025.4.0
  - pandas=2.2.3
  - pyproj=3.6.1
  - metpy=1.7.0
  - scipy=1.15.2
  - scikit-image=0.25.2
  - zarr=2.18.7
  - jupyter